### ISSUE TITLE
TypeError: Cannot do inplace boolean setting on mixed-types with a non np.nan value

### ISSUE THREAD

**Issue by anupjn** [DTOcean/dtocean-electrical#11] opened 2019-07-11 11:38 UTC
Hi, I get the following error (copied below) on this line of the code (please see link below) when trying to run the example file electrical_run.py. 

I managed to get around the error by replacing the line in the local version of the code to 
matrix = matrix.apply(lambda x: [y if y == 0 else 1 for y in x])

I am using Python 2.7.16.

Is this showing some compatibility issues with the versions of different packages I have installed compared to versions used when DTO 2 was written? 

**************
Line in code
**************

https://github.com/DTOcean/dtocean-electrical/blob/9ac69a947c02aebf8f4e69ebd5740b062fb7cf9e/dtocean_electrical/inputs.py#L1034

**************
Error message
**************
In [1]: runfile('C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py', wdir='C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples')
2019-07-11 12:24:11,819 - INFO - dtocean_electrical - Begin logging for dtocean_electrical.
C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\polite\configuration.py:305: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(conf)
Traceback (most recent call last):

  File "<ipython-input-1-9df99109f450>", line 1, in <module>
    runfile('C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py', wdir='C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples')

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/anambiar/DTOceanPlus/DTOcean1_Electrical_System_Architecture/examples/electrical_run.py", line 215, in <module>
    installation_tool)

  File "C:\Users\anambiar\DTOceanPlus\DTOcean1_Electrical_System_Architecture\dtocean_electrical\inputs.py", line 1010, in __init__
    deepcopy(equipment_soil_compatibility))

  File "C:\Users\anambiar\DTOceanPlus\DTOcean1_Electrical_System_Architecture\dtocean_electrical\inputs.py", line 1036, in binary_compatibility_matrix
    matrix[matrix > 0] = 1

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\pandas\core\frame.py", line 3365, in __setitem__
    self._setitem_frame(key, value)

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\pandas\core\frame.py", line 3412, in _setitem_frame
    self._check_inplace_setting(value)

  File "C:\Users\anambiar\AppData\Local\Continuum\anaconda3\envs\py2\lib\site-packages\pandas\core\generic.py", line 5190, in _check_inplace_setting
    raise TypeError('Cannot do inplace boolean setting on '

TypeError: Cannot do inplace boolean setting on mixed-types with a non np.nan value

**************
**************

**Comment by H0R5E** [comment] 2019-07-11 12:22
Probable duplicate of #12. Closing.

**Closed as completed by H0R5E** 2019-07-11 12:22 UTC
Labels: duplicate
